[project]
name = "pyrogue"
version = "0.1.0"
requires-python = ">=3.12"
description = "ASCII Roguelike"
authors = [{name = "Andrew Butler"}]

[project.scripts]
pyrogue = "pyrogue.pyrogue:main"

[tool.setuptools.package-data]
"pyrogue" = ["gamedata/*.txt"]